name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: "Node ${{ matrix.node }} on Linux: Lint"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: |
          npm run commitlint -- \
          --verbose \
          --from `git merge-base origin/master $GITHUB_SHA`
