name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Test and Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.KARMARUNNERBOT_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: browser-actions/setup-firefox@latest
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npm run test
      - run: npm run release
