name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: "Node ${{ matrix.node }} on Linux: Test and Lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run test
  windows:
    name: "Node ${{ matrix.node }} on Windows: Test and Lint"
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run test
